// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfvcfxxfxctwylddkzul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdmNmeHhmeGN0d3lsZGRrenVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0MjYxODEsImV4cCI6MjA3NTAwMjE4MX0.KVZYR32h9SogqPfzEfDAxDRESUkSvu7g1qF_ky8me3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});